#!/usr/bin/env bash
set -euo pipefail
smoke_temp="$(mktemp -d)"
export RUNNER_TEMP="$smoke_temp"

# `scripts/serve-dist.ts` rather than `astro preview`: preview manages
# a background daemon, which leaves "has the server started" ambiguous
# and can outlive the step. This serves the same `dist/` in the
# foreground on 0.0.0.0, so the IPv4 probes below always reach it.
PORT=4321 bun run scripts/serve-dist.ts &
server=$!
trap 'kill "${server}" 2>/dev/null || true; rm -rf "$smoke_temp"' EXIT

# Readiness loop, deliberately NOT `curl --retry`: this distinguishes
# "not up yet" from "up but broken", so a real 500 fails fast instead
# of being retried into a timeout.
timeout 90 bash -c 'until curl -fsS -o /dev/null http://127.0.0.1:4321/; do sleep 1; done'

# Assert on CONTENT, not just status — a 200 error page would sail
# through a status-only check.
#
# The body goes to a file rather than into `curl ... | grep -q`:
# grep -q exits at the first match, curl then dies of SIGPIPE with
# exit 23, and `pipefail` turns that into a failure. Whether it trips
# depends on response size and timing, so the piped form is
# intermittently red rather than reliably broken.
#
# Every route the site publishes is listed: the Danish default locale
# and the /en prefix, which is where a routing or i18n regression
# shows up first.
for path in / /om /privatliv /hjaelp /en/ /en/about /en/privacy /en/help; do
  echo "==> ${path}"
  curl -fsS -m 10 -o "${RUNNER_TEMP}/page.html" "http://127.0.0.1:4321${path}"
  grep -q '<title>' "${RUNNER_TEMP}/page.html" \
    || { echo "SMOKE FAILED: ${path} served no <title>"; exit 1; }
done

# The Content Security Policy is generated by Astro from
# `security.csp` in astro.config.mjs and is the enforcement half of
# the product's no-backend privacy guarantee. A config change that
# drops it is silent in every other check here, so assert it directly.
echo "==> CSP meta on /"
curl -fsS -m 10 -o "${RUNNER_TEMP}/home.html" "http://127.0.0.1:4321/"
grep -qi 'http-equiv="content-security-policy"' "${RUNNER_TEMP}/home.html" \
  || { echo "SMOKE FAILED: / served no CSP meta tag"; exit 1; }
